version: "3.9"
services:
  cli:
    build: cli
    volumes:
      - ../app:/workspaces/laravel
    userns_mode: keep-id

  fpm:
    build: fpm
    volumes:
      - ../app:/workspaces/laravel
    ports: 
      - 9000:9000

  nginx:
    build: nginx
    volumes:
      - ../app:/workspaces/laravel
    ports:
      - 8080:80
    depends_on:
      - fpm

  postgres:
    image: docker.io/library/postgres:alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
